AllCops:
  TargetRubyVersion: 2.2.0

Documentation:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/Lambda:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StderrPuts:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
# re-enable this when our min ruby is 2.3
Layout/IndentHeredoc:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 50
