AllCops:
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 30

Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/Documentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StderrPuts:
  Enabled: false
