require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleDescribes:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/Documentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StderrPuts:
  Enabled: false
