cache: bundler
language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6

before_install: gem update --remote bundler
bundler_args: --jobs 3
install: bundle install --jobs 3

script:
  - bundle exec rubocop --fail-level autocorrect
  - bundle exec rake
